### ISSUE TITLE
[IDEA]

### ISSUE THREAD

**Issue by EinfachEli08** [RusticBard/Skeuowaita#25]
There is a gnome wallpaper, that is pretty cool. Could you create one like this, with light and dark mode, but with your icons?

This idea doesn't have to be implemented 

![image](https://github.com/Frostbitten-jello/Skeuowaita/assets/100494326/7b38ca30-220c-4fbe-8b1c-71e81515d2d7)

![image](https://github.com/Frostbitten-jello/Skeuowaita/assets/100494326/f31578b4-fdfb-4777-be83-db5ad458794a)

Thoughts about this would be appreciated :D

**Comment by RusticBard** [comment]
I dont know how to achieve this pixelated look but looks cool ... would love to work on something like this but lets see >< I am kinda occupied with studies so won't promise anything rn
