### ISSUE TITLE
[ICON] Obsidian (md.obsidian.Obsidian)

### ISSUE THREAD

**Issue by 42Willow** [RusticBard/Skeuowaita#28]
Current icon:
![image](https://github.com/Frostbitten-jello/Skeuowaita/assets/70784752/1f2d050e-db07-4a41-aeb1-0482117ea554)

**Comment by RusticBard** [comment]
I have added a temporary icon for obsidian as I am also using it and it was sticking out as an eyesore for me ... but will design something nicer as I work on it more :)
