### ISSUE TITLE
[ICON] Anki (net.ankiweb.Anki)

### ISSUE THREAD

**Issue by 42Willow** [RusticBard/Skeuowaita#30]
Current old icon:
![image](https://github.com/Frostbitten-jello/Skeuowaita/assets/70784752/a657fc19-a936-48e4-be34-0b274abbe876)
Newer android icon to go off:
![ankidroid_logo](https://github.com/Frostbitten-jello/Skeuowaita/assets/70784752/f503d391-6bf3-48c3-ac60-41a3f5cc92e2)

**Comment by RusticBard** [comment]
can you add the name of the icon file?

**Comment by RusticBard** [comment]
just added then icon, let me know what you think :)
