### ISSUE TITLE
[ICON] Aseprite

### ISSUE THREAD

**Issue by 42Willow** [RusticBard/Skeuowaita#33]
No flatpak (and hence no ID, I think...) as of writing. But users can still manually change the icon in the .desktop entry.

![ase256](https://github.com/Frostbitten-jello/Skeuowaita/assets/70784752/94ae9cb1-2a75-425e-90a2-e360d10c5e73)

**Comment by RusticBard** [comment]
is "Aseprite" the name in the `.desktop` file?

**Comment by RusticBard** [comment]
I have added the icon as "Aseprite" let me know what u think :)

**Comment by 42Willow** [comment]
Looks good to me!
![](https://raw.githubusercontent.com/RusticBard/Skeuowaita/1537a728a8c993e2f9cf37023a5247789a4f74ae/512x512/apps/Aseprite.png)
