### ISSUE TITLE
[ICON] RustRover (com.jetbrains.RustRover) & Fleet (com.jetbrains.Fleet)

### ISSUE THREAD

**Issue by CraneCristal** [RusticBard/Skeuowaita#35]
Current icon (RustRover):
![image](https://github.com/Frostbitten-jello/Skeuowaita/assets/119360710/ffdd4d42-d3d0-441e-acf7-6a8e914794c4)

Current icon (Fleet):
![image](https://github.com/Frostbitten-jello/Skeuowaita/assets/119360710/059a757f-298d-4273-b75f-f7206cd9b305)

**Comment by RusticBard** [comment]
added both the icons ... let me know what you think :)
